create schema "public";
create table "public"."categories" (
  "category" int generated by default as identity not null,
  "categoryname" varchar(50) not null,
  constraint "categories_pkey"
    primary key ("category")
);
create table "public"."cust_hist" (
  "customerid" int not null,
  "orderid" int not null,
  "prod_id" int not null
);
create table "public"."customers" (
  "customerid" int generated by default as identity not null,
  "firstname" varchar(50) not null,
  "lastname" varchar(50) not null,
  "address1" varchar(50) not null,
  "address2" varchar(50) null,
  "city" varchar(50) not null,
  "state" varchar(50) null,
  "zip" int null,
  "country" varchar(50) not null,
  "region" smallint not null,
  "email" varchar(50) null,
  "phone" varchar(50) null,
  "creditcardtype" int not null,
  "creditcard" varchar(50) not null,
  "creditcardexpiration" varchar(50) not null,
  "username" varchar(50) not null,
  "password" varchar(50) not null,
  "age" smallint null,
  "income" int null,
  "gender" varchar(1) null,
  constraint "customers_pkey"
    primary key ("customerid")
);
create table "public"."inventory" (
  "prod_id" int not null,
  "quan_in_stock" int not null,
  "sales" int not null,
  constraint "inventory_pkey"
    primary key ("prod_id")
);
create table "public"."orderlines" (
  "orderlineid" int not null,
  "orderid" int not null,
  "prod_id" int not null,
  "quantity" smallint not null,
  "orderdate" date not null
);
create table "public"."orders" (
  "orderid" int generated by default as identity not null,
  "orderdate" date not null,
  "customerid" int null,
  "netamount" numeric(12, 2) not null,
  "tax" numeric(12, 2) not null,
  "totalamount" numeric(12, 2) not null,
  constraint "orders_pkey"
    primary key ("orderid")
);
create table "public"."products" (
  "prod_id" int generated by default as identity not null,
  "category" int not null,
  "title" varchar(50) not null,
  "actor" varchar(50) not null,
  "price" numeric(12, 2) not null,
  "special" smallint null,
  "common_prod_id" int not null,
  constraint "products_pkey"
    primary key ("prod_id")
);
create table "public"."reorder" (
  "prod_id" int not null,
  "date_low" date not null,
  "quan_low" int not null,
  "date_reordered" date null,
  "quan_reordered" int null,
  "date_expected" date null
);
alter table "public"."cust_hist"
  add constraint "fk_cust_hist_customerid"
    foreign key ("customerid")
    references "public"."customers" ("customerid");
alter table "public"."orderlines"
  add constraint "fk_orderid"
    foreign key ("orderid")
    references "public"."orders" ("orderid");
alter table "public"."orders"
  add constraint "fk_customerid"
    foreign key ("customerid")
    references "public"."customers" ("customerid");
create unique index "categories_pkey" on "public"."categories"("category" asc);
create index "ix_cust_hist_customerid" on "public"."cust_hist"("customerid" asc);
create unique index "customers_pkey" on "public"."customers"("customerid" asc);
create unique index "ix_cust_username" on "public"."customers"("username" asc);
create unique index "inventory_pkey" on "public"."inventory"("prod_id" asc);
create unique index "ix_orderlines_orderid" on "public"."orderlines"(
  "orderid" asc,
  "orderlineid" asc
);
create index "ix_order_custid" on "public"."orders"("customerid" asc);
create unique index "orders_pkey" on "public"."orders"("orderid" asc);
create index "ix_prod_category" on "public"."products"("category" asc);
create index "ix_prod_special" on "public"."products"("special" asc);
create unique index "products_pkey" on "public"."products"("prod_id" asc);